# .project metadata for CloudNativePG
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add social networks

schema_version: "1.0.0"
slug: "cloudnativepg"
name: "CloudNativePG"
description: "CloudNativePG is a comprehensive platform designed to seamlessly manage PostgreSQL databases within Kubernetes environments, covering the entire operational lifecycle from initial deployment to ongoing maintenance"
type: "project"
project_lead: "@cloudnative-pg/maintainers"
cncf_slack_channel: "#cloudnativepg-users"

maturity_log:
  - phase: "sandbox"
    date: "2025-01-21T15:30:03.000Z"
    issue: "https://github.com/cncf/sandbox/issues/128"

repositories:
  - "https://github.com/cloudnative-pg/api"
  - "https://github.com/cloudnative-pg/artifacts"
  - "https://github.com/cloudnative-pg/barman-cloud"
  - "https://github.com/cloudnative-pg/charts"
  - "https://github.com/cloudnative-pg/cloudnative-pg"
  - "https://github.com/cloudnative-pg/cloudnative-pg.github.io"
  - "https://github.com/cloudnative-pg/cnpg-i"
  - "https://github.com/cloudnative-pg/cnpg-i-machinery"
  - "https://github.com/cloudnative-pg/docs"
  - "https://github.com/cloudnative-pg/governance"
  - "https://github.com/cloudnative-pg/pgbouncer-containers"
  - "https://github.com/cloudnative-pg/plugin-barman-cloud"
  - "https://github.com/cloudnative-pg/postgis-containers"
  - "https://github.com/cloudnative-pg/postgres-containers"
  - "https://github.com/cloudnative-pg/postgres-extensions-containers"

website: "https://www.cloudnative-pg.io/"

artwork: "https://landscape.cncf.io/logos/cloudnative-pg.svg"

adopters:
  path: "https://github.com/cloudnative-pg/cloudnative-pg/blob/main/ADOPTERS.md"

# TODO: Add package manager identifiers if your project is distributed via registries
package_managers:
  docker: "cloudnative-pg/cloudnative-pg"

social:
  twitter: "https://x.com/CloudNativePg"
  # TODO: Add BlueSky, Mastodon

security:
  policy:
    path: "https://github.com/cloudnative-pg/cloudnative-pg/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/cloudnative-pg/cloudnative-pg/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/cloudnative-pg/cloudnative-pg/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/cncf/foundation/blob/main/code-of-conduct.md"

legal:
  license:
    path: "https://github.com/cloudnative-pg/cloudnative-pg/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/cloudnative-pg/cloudnative-pg/blob/main/README.md"

landscape:
  category: "App Definition and Development"
  subcategory: "Database"
